/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huigou_loader_HuiGouNative */

#ifndef _Included_com_huigou_loader_HuiGouNative
#define _Included_com_huigou_loader_HuiGouNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huigou_loader_HuiGouNative
 * Method:    findClass
 * Signature: (Lcom/huigou/loader/HuiGouClassLoader;Ljava/lang/String;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_com_huigou_loader_HuiGouNative_findClass
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
